### ISSUE TITLE
debug replication failure

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_robots#98]

**Comment by tallenaz** [comment]
A worker will only be able to process a handful of jobs from the delivery queue, and then stall out, until you restart the worker, at which point it will again grab a handful of jobs, replicate, and stall out.

We've verified that this is so whether or not we're using `resque-pool`.

`nrdebug` suggests a possible lead:

```
Ruby Backtrace(s):
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/multipart_file_uploader.rb:131:in `block (2 levels) in upload_in_threads'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/client.rb:5909:in `upload_part'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/seahorse/client/request.rb:70:in `send_request'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/seahorse/client/plugins/response_target.rb:23:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/rest/handler.rb:8:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/bucket_dns.rb:33:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/expect_100_continue.rb:22:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:13:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/md5s.rb:28:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/dualstack.rb:34:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/retry_errors.rb:138:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/redirects.rb:18:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/s3_signer.rb:87:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/s3_host_id.rb:15:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/plugins/s3_signer.rb:53:in `call'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-core-3.22.1/lib/aws-sdk-core/plugins/signature_v4.rb:112:in `apply_signature'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sigv4-1.0.3/lib/aws-sigv4/signer.rb:215:in `sign_request'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sigv4-1.0.3/lib/aws-sigv4/signer.rb:476:in `sha256_hexdigest'
        from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sdk-s3-1.9.1/lib/aws-sdk-s3/file_part.rb:36:in `read'
/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/aws-sigv4-1.0.3/lib/aws-sigv4/signer.rb:476: [BUG] object allocation during garbage collection phase
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
```
